name: tests

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -r requirements-test.txt
      # Install `update-conf.py` script to make it available to the
      # 'test_script.py' test module.
      - run: python setup.py develop
      - run: make check
      - run: sudo PATH=$PATH make test-with-coverage
      - run: coverage lcov
      - uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
